### ISSUE TITLE
Add user configurable way to get process title

### ISSUE THREAD

**Issue by dfrankland** [dfrankland/hyperterm-tab-icons#17]
As reported by @Arttse here: https://github.com/dfrankland/hyper-tab-icons/issues/15#issuecomment-269406741

Using a shell that doesn't put the process as the first word in the title string causes `hyper-tab-icons` from changing the icon from the default.

Here's an example (provided by @Arttse) of use with the `zsh` shell:
![](https://cloud.githubusercontent.com/assets/7123950/21511494/b7a6fb84-ccb2-11e6-914a-321410eb86af.gif)

This is the line that should be updated:
https://github.com/dfrankland/hyper-tab-icons/blob/master/index.js#L47

As default the title should be found using ` title.split(' ')[0]`, but should be able to be configured in `~/.hyper.js` settings.

**Comment by dfrankland** [comment]
This should be fixed with `hyper-tab-icons@1.1.3` now. See here: https://github.com/dfrankland/hyper-tab-icons#configtabiconsprocessnameregex

**Comment by Arttse** [comment]
Thanks! It works like a charm!

**Comment by fyodoriv** [comment]
Hey, looks like I'm having the same issue as on that .gif, but with `fish` on Mac. Just to be sure I've tried with only enabling this plugin, also tried with and without 
```js
  tabIcons: {
    mapIcons: {
      nodejs: ['node'],
    }
  }
```
after `plugins` section. When launching `node` I still get the bash icon in the tab.

**Comment by dfrankland** [comment]
@cbrwizard, I also use `fish` on Mac. This should work out-of-the-box for `fish`. Do you have any custom settings to change the title? Mind sharing a screenshot or something?

**Comment by alexh** [comment]
Having this issue as well

**Comment by dfrankland** [comment]
@alexh is this actually the same issue? The feature mentioned has already been added: https://github.com/dfrankland/hyper-tab-icons#configtabiconsprocessnameregex
